# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tom Doidge
tagline:          Software Engineer
url:              http://tomdoidge.com/
paginate:         1
baseurl:          http://tomdoidge.com/
author:
  name:           Tom Doidge
  url:            http://tomdoidge.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/tombdoidge/tombdoidge.github.io
